extends Node

enum RESOURCE_TYPE { FOOD, GOLD }
enum UNIT_TYPE { SETTLER, WORKER, WARRIOR, ARCHER }
enum BUILDING_TYPE { SETTLEMENT, OUTPOST, HUNTING_CAMP, MINING_CAMP }
enum ABILITY_TYPES { CONSTRUCT_BUILDING, RESUME_CONSTRUCTION, BUILD_UNIT }
enum TARGET_TYPE { EMPTY, FRIENDLY_UNIT, FRIENDLY_BUILDING, FRIENDLY_PLAYER_ENTITY, HOSTILE_UNIT, HOSTILE_BUILDING, HOSTILE_PLAYER_ENTITY, RESOURCE_NODE, ANY }
